### PR TITLE
Restructuring repo

### PR DESCRIPTION
**Pull request by erogluorhan**
- Remove CircleCI configurations
- Add Github Actions workflow instead (.github/workflows/ci.yml)
- Restructure folders and env files (move into folder `build_envs`, and remove some unnecessary env files such as testenv2.yml) and modifie some docs in relation.

### CODE REVIEW

**Comment by erogluorhan** [comment]
@michaelavs FYI: The failing CI tests below are from the removed CircleCI configuration, and we are intorudcing several Github actions instead, which are passing in this PR. So, the failing CircleCI tests shouldn't be an issue:

image

**Review by anissa111 — COMMENTED** [review]
I'm not very familiar with this repo, but it looks like everything is working from my end. My only question is whether /test/ci_tests/ can also be removed since circleci was replaced.

**Comment by erogluorhan** [comment]
> I'm not very familiar with this repo, but it looks like everything is working from my end.

Thanks! Yes, CircleCI build tests are replicated in the new `ci.yml` and these tests all pass. 

> My only question is whether /test/ci_tests/ can also be removed since circleci was replaced.

No, it shouldn't be removed because it is for general CI testing, nothing specific to CircleCI.

**Comment by anissa111** [comment]
Ah! That makes sense

**Review by anissa111 — APPROVED** [review]

**Pull request merged**
