### PR TITLE
Fix proj params. Issue #127

### PR DESCRIPTION
**Pull request by pgamez**
Solves issue #127

### CODE REVIEW

**Comment by michaelavs** [comment]
Hi,
While reviewing your PR (and its associated issue), I was wondering if you could clarify for me the need to change CF formatting from semi-major axis to earth radius? Both produce the same value when printed, so I wasn't sure if the change is exactly necessary. I do agree with the proj4 format change and I can see why that may become an issue for some users, along with wanting to maintain accuracy of the variable/unit.

**Comment by pgamez** [comment]
Hi Michaela,

Thank you for your message :)

Actually, `semi_major_axis` has a different behaviour than `earth_radius`. This code will parse a projection in 5 cases:

1. Without ellipsoid (i.e.: using the default `WGS84`)
2. Setting semi-major axis
3. Setting earth_radius
4. Setting both semi-major axis and earth radius
5. Setting semi-amojr axis and inverse flattening

```python
import pyproj as pj

cf = [
    {
        'grid_mapping_name': 'lambert_conformal_conic',
        'standard_parallel': [60, 30],
        'longitude_of_central_meridian': 0,
        'latitude_of_projection_origin': 45,
    },
    {
        'grid_mapping_name': 'lambert_conformal_conic',
        'standard_parallel': [60, 30],
        'longitude_of_central_meridian': 0,
        'latitude_of_projection_origin': 45,
        'semi_major_axis': 6370000.0,
    },
    {
        'grid_mapping_name': 'lambert_conformal_conic',
        'standard_parallel': [60, 30],
        'longitude_of_central_meridian': 0,
        'latitude_of_projection_origin': 45,
        'earth_radius': 6370000.0,
    },
    {
        'grid_mapping_name': 'lambert_conformal_conic',
        'standard_parallel': [60, 30],
        'longitude_of_central_meridian': 0,
        'latitude_of_projection_origin': 45,
        'semi_major_axis': 6370000.0,
        'earth_radius': 6370000.0,
    },
    {
        'grid_mapping_name': 'lambert_conformal_conic',
        'standard_parallel': [60, 30],
        'longitude_of_central_meridian': 0,
        'latitude_of_projection_origin': 45,
        'semi_major_axis': 6370000.0,
        'inverse_flattening': 0.0,
    },
]

for i, attrs in enumerate(cf):
    print(i+1, pj.CRS.from_cf(attrs).to_proj4())
```

The execution shows that the only cases that are correct are the 3rd and the 5th:

```
$ python3 test.py
test.py:43: UserWarning: You will likely lose important projection information when converting to a PROJ string from another format. See: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems
  print(i+1, pj.CRS.from_cf(attrs).to_proj4())
1 +proj=lcc +lat_0=45 +lon_0=0 +lat_1=60 +lat_2=30 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs +type=crs
2 +proj=lcc +lat_0=45 +lon_0=0 +lat_1=60 +lat_2=30 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs +type=crs
3 +proj=lcc +lat_0=45 +lon_0=0 +lat_1=60 +lat_2=30 +x_0=0 +y_0=0 +R=6370000 +units=m +no_defs +type=crs
4 +proj=lcc +lat_0=45 +lon_0=0 +lat_1=60 +lat_2=30 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs +type=crs
5 +proj=lcc +lat_0=45 +lon_0=0 +lat_1=60 +lat_2=30 +x_0=0 +y_0=0 +R=6370000 +units=m +no_defs +type=crs
```

So, it seems 2 possible options:

- earth radius, or
- semimajor axis and inverse flattening

**Comment by pgamez** [comment]
BTW, there is another issue
It seems that the projection parameters of type "numpy.float32" (as they as in the netcdf file) cannot be used with pyproj:

```python
from netCDF4 import Dataset
import wrf
import pyproj as pj

filename = 'wrfout_d03_2020-09-01_20:00:00'

with Dataset(filename) as wrfin:
    proj_params = wrf.get_proj_params(wrfin)

proj = wrf.getproj(**proj_params)
cf = proj.cf()

print(cf)
print(pj.CRS.from_cf(cf).to_proj4())
```

This is the output:

```
{'grid_mapping_name': 'lambert_conformal_conic', 'standard_parallel': [46.47, 33.13], 'longitude_of_central_meridian': -2.8, 'latitude_of_projection_origin': 39.8, 'semi_major_axis': 6370000.0}
Traceback (most recent call last):
  File "git.py", line 17, in <module>
    print(pj.CRS.from_cf(cf).to_proj4())
  File "/home/pgamez/miniconda3/envs/devel/lib/python3.8/site-packages/pyproj/crs/crs.py", line 768, in from_cf
    conversion=conversion_method(in_cf),
  File "/home/pgamez/miniconda3/envs/devel/lib/python3.8/site-packages/pyproj/crs/_cf1x8.py", line 166, in _lambert_conformal_conic
    return LambertConformalConic2SPConversion(
  File "/home/pgamez/miniconda3/envs/devel/lib/python3.8/site-packages/pyproj/crs/coordinate_operation.py", line 409, in __new__
    return cls.from_json_dict(lcc_json)
  File "pyproj/_crs.pyx", line 2048, in pyproj._crs.CoordinateOperation.from_json_dict
  File "/home/pgamez/miniconda3/envs/devel/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/home/pgamez/miniconda3/envs/devel/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/pgamez/miniconda3/envs/devel/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/pgamez/miniconda3/envs/devel/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type float32 is not JSON serializable
```

But I don't know if the issue is at wrf-pythons side or at pyprojs side...
However I will report this problem to pyproj as well

greetings
pedro

**Comment by michaelavs** [comment]
> * earth

After looking into the proj4 website and getting a better feel for what the changes would be doing, I think I feel pretty confident in the changes you have suggested. I'll be reviewing them and should be able to merge them soon!

**Comment by pgamez** [comment]
Thank you very much Michaela!
greetings :)

**Review by michaelavs — APPROVED** [review]

**Pull request merged**
