### PR TITLE
BLD: Add pyproject.toml

### LINKED ISSUE #237: error when install wrf-python
Error when i use pip to install wrf-python:
```shell
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple/
Collecting wrf-python
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/19/b9/ac6886e7995a9c83f393f758fd4803ab13bda0e57f8d3540f6d3a9f070db/wrf-python-1.3.4.1.tar.gz (1.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      /root/.cache/pypoetry/virtualenvs/python-plot-u4OVFNWo-py3.8/bin/python: No module named pip
      Traceback (most recent call last):
        File "/root/.cache/pypoetry/virtualenvs/python-plot-u4OVFNWo-py3.8/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/root/.cache/pypoetry/virtualenvs/python-plot-u4OVFNWo-py3.8/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/root/.cache/pypoetry/virtualenvs/python-plot-u4OVFNWo-py3.8/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-_nr8l14r/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-_nr8l14r/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-_nr8l14r/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-_nr8l14r/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 17, in <module>
      ModuleNotFoundError: No module named 'numpy'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

I try to install it through source code referencing to [documentation](https://wrf-python.readthedocs.io/en/latest/installation.html#installing-via-source-code), but it still raised the same error

And i'm 100% percent sure that i have numpy in my virtualenv(created by poetry), and i run `pip install wrf-python` while the virtualenv is activated(in the `poetry shell`) 
image

### PR DESCRIPTION
**Pull request by DWesl**
This might close #237 by specifying NumPy as a build dependency before starting the setup script.

I moved as much configuration to `pyproject.toml` as I could as an initial step to converting the build to a system available on Python 3.12.

### CODE REVIEW

**Comment by VascoSch92** [comment]
You could also deplace the requirements.txt inside the pyproject ;)

**Comment by DWesl** [comment]
As in, delete [line 55 of pyproject.toml](https://github.com/NCAR/wrf-python/pull/241/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R55) and move the contents of `requirements.txt` into `[project].dependencies?

https://github.com/NCAR/wrf-python/blob/cec1f70ceff9e4e051e4e0ed73104c60220ab0eb/setup.py#L61-L73
I meant to ask earlier how important installing only mock on RTD was.
[The specification](https://peps.python.org/pep-0508/) doesn't seem to allow conditioning requirements on environment variables, and I'm not sure TOML does either, unless there's a way for `wrf-python[rtd]` to have fewer dependencies than `wrf-python`.

**Comment by VascoSch92** [comment]
> As in, delete [line 55 of pyproject.toml](https://github.com/NCAR/wrf-python/pull/241/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R55) and move the contents of requirements.txt into `[project].dependencies?
Yes, probably you should also change `pip install -r requirements.txt` in `pip install -r .` everywhere

**Comment by kafitzgerald** [comment]
Thanks for the PR!

I was hoping to get this updated and merged yesterday, but need to need to look into why the Ubuntu CI checks are failing. 
 I'll try to take a deeper look later this week or next unless someone beats me to it.

**Review by kafitzgerald — APPROVED** [review]
Looks like the lingering failures were just a fluke w/ CI.  

This all looks good to me.

**Comment by erogluorhan** [comment]
Great to see the issues of this pR have been fixed. Looks good to me

**Pull request merged**
